-- AlterTable
ALTER TABLE "Comment" ALTER COLUMN "createdAt" DROP DEFAULT,
ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Tag" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
