import 'dotenv/config';

const {
  NODE_ENV,
  HOST,
  PORT,
  FPORT,
  JWT_SECRET,
  SALT_ROUNDS,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REFRESH_TOKEN,
  GOOGLE_CALLBACK_URL,
  FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET,
  FACEBOOK_CALLBACK_URL,
  /*EMAIL_USER,
  EMAIL_NAME,
  BACKEND,
  FRONTEND*/
} = process.env;

const config = {
  HOST: NODE_ENV === 'production' && HOST ? HOST : 'localhost',
  PORT: NODE_ENV === 'production' && PORT ? PORT : 3001,
  FPORT: NODE_ENV === 'production' && FPORT ? FPORT : 5173,
  JWT_SECRET: NODE_ENV === 'production' && JWT_SECRET ? JWT_SECRET : 'JWT_SECRET_DEV',
  SALT_ROUNDS: NODE_ENV === 'production' && SALT_ROUNDS ? SALT_ROUNDS : 10,
  GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID ? GOOGLE_CLIENT_ID : '',
  GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET ? GOOGLE_CLIENT_SECRET : '',
  GOOGLE_REFRESH_TOKEN: GOOGLE_REFRESH_TOKEN ? GOOGLE_REFRESH_TOKEN : '',
  GOOGLE_CALLBACK_URL: NODE_ENV === 'production' && GOOGLE_CALLBACK_URL ? GOOGLE_CALLBACK_URL : 'http://localhost:3001/signin/google/callback',
  FACEBOOK_APP_ID: FACEBOOK_APP_ID ? FACEBOOK_APP_ID : '',
  FACEBOOK_APP_SECRET: FACEBOOK_APP_SECRET ? FACEBOOK_APP_SECRET : '',
  FACEBOOK_CALLBACK_URL: NODE_ENV === 'production' && FACEBOOK_CALLBACK_URL ? FACEBOOK_CALLBACK_URL : 'http://localhost:3000/signin/facebook/callback',
  FRONTEND: NODE_ENV === 'production' && FRONTEND ? FRONTEND : 'http://localhost:5173'
  /*EMAIL_USER: NODE_ENV === 'production' && EMAIL_USER ? EMAIL_USER : '',
  EMAIL_NAME: NODE_ENV === 'production' && EMAIL_NAME ? EMAIL_NAME : 'User manager',
  BACKEND: NODE_ENV === 'production' && BACKEND ? BACKEND : 'http://localhost:3001',*/
};

export default config